/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        int b =888;
        int c =10;
        String abc = "충돌안남";
        return abc;
        //?  zzzzzzzzzzzzzzzz

    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("훌랄라 훌랄라 호!");
        System.out.println("아 세이 권");
        System.out.println("유 세이 형은");
        System.out.println("안진호추가함!!!");
        int a;
        System.out.println(2_342_1234);
        String ban;
        System.out.println("김종규 잘생겼다");
    }
}
