/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        int b =888;
        int c =10;
        String abc = "fucking merge tool";
        String eee = "eee";
        String abcd = "충돌남";
        String d = "d";
        int f = 22;
        return abc;
        
        
        //
        //머지툴테스트
        //?
        //?  zzzzzzzzzzzzzzzz

    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("훌랄라 훌랄라 호!");
        System.out.println("안진호추가함!!!");
        int a;
        System.out.println(2_342_1234);
        String ban;
        System.out.println("김종규 잘생겼다");
    }
}
